### ISSUE TITLE
<PaymentElement /> not mounting (or binding)

### ISSUE THREAD

**Issue by nmalchy** [joshnuss/sveltekit-stripe-subscriptions#2]
Hey another issue I'm encountering (after just getting past the other one), getting the error "+page.svelte:365 Uncaught (in promise) IntegrationError: Invalid value for stripe.confirmPayment(): elements should have a mounted Payment Element or Express Checkout Element." after I fill in the credit card payment info and press the "Pay" button; not sure why this is happening as it looks like the UI clearly mounted, I also tried both API versions.. I used fake info from [here ](https://stripe.com/docs/testing?testing-method=card-numbers#visa)also

Would super appreciate help as I'm very new to Svelte and Stripe

Here is my code for context:

// src/routes/checkout/payment/+page.svelte
```
<script lang="ts">
    import { PUBLIC_STRIPE_KEY } from '$env/static/public'
    import { onMount } from 'svelte'
    import { loadStripe, type Stripe, type StripeElements } from '@stripe/stripe-js'
    import { Elements, PaymentElement } from 'svelte-stripe'
  
    // data from server
    export let data
  
    // destructure server data
    $: ({ clientSecret, returnUrl } = data)
  
    let stripe: Stripe | null
  
    let elements: StripeElements
  
    // when component mounts
    onMount(async () => {
      // load the Stripe client
      stripe = await loadStripe(PUBLIC_STRIPE_KEY)
      console.log('stripe:', stripe)
    })
  
    // handle form submission
    async function submit() {
      // ask Stripe to confirm the payment
      const { error } = await stripe!.confirmPayment({
        // pass instance that was used to create the Payment Element
        elements,
        // specify where to send the user when payment succeeeds
        confirmParams: {
          return_url: returnUrl
        }
      })
  
      if (error) {
        // handle error
        console.error(error)
      }
    }
</script>
  
<h1>Payment</h1>

{#if stripe}
  <form on:submit|preventDefault={submit}>
    <!-- container for Stripe components -->
    <Elements {stripe} {clientSecret} bind:elements>

      <!-- display payment related fields -->
      <PaymentElement />
    </Elements>

    <button>Pay</button>
  </form>
{:else}
  Loading Stripe...
{/if}
```

my console.log:
![image](https://github.com/joshnuss/sveltekit-stripe-subscriptions/assets/50896885/e1066bdf-03d5-4b37-92f1-12bbdd23b315)

**Comment by joshnuss** [comment]
Hi @nmalchy,

Feel free to ask away! 

For trials (setup intents), I believe `confirmPayment()` should change to [`confirmSetup()`](https://stripe.com/docs/js/setup_intents/confirm_setup).

**Comment by nmalchy** [comment]
> Hi @nmalchy,
> 
> Feel free to ask away!
> 
> For trials (setup intents), I believe `confirmPayment()` should change to [`confirmSetup()`](https://stripe.com/docs/js/setup_intents/confirm_setup).

Ok I'll try that once I go reconfig using the other comment you made however this above issue is using a non-trial subscription, so not sure exactly why this error is occurring still, you don't encounter the above error when running the code and pressing "Pay"?

**Comment by joshnuss** [comment]
I think it is an issue with some changes I made on svelte-stripe last week.

I see the same issue on the demo for PaymentElement:
https://www.sveltestripe.com/examples/payment-element

In the meantime, you can downgrade `svelte-stripe` to [v0.0.24](https://www.npmjs.com/package/svelte-stripe/v/0.0.24) so you're not blocked

**Comment by nmalchy** [comment]
> I think it is an issue with some changes I made on svelte-stripe last week.
> 
> I see the same issue on the demo for PaymentElement: https://www.sveltestripe.com/examples/payment-element
> 
> In the meantime, you can downgrade `svelte-stripe` to [v0.0.24](https://www.npmjs.com/package/svelte-stripe/v/0.0.24) so you're not blocked

Awesome, I will downgrade in the meantime. Thank you for looking into this!

**Comment by joshnuss** [comment]
Thanks for reporting this issue.

It's now fixed!
